# explains how both apps/api and apps/web are seperate node projects in the same repo (a monorepo)
packages:
  - apps/*

onlyBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - esbuild
  - prisma
  - sharp
  - unrs-resolver
